In [1]:
!pip install pyarrow fastparquet

Collecting pyarrow
  Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: fastparquet in /home/new/market-prediction/market-env/lib/python3.12/site-packages (2026.3.0)
Requirement already satisfied: pandas>=1.5.0 in /home/new/market-prediction/market-env/lib/python3.12/site-packages (from fastparquet) (2.3.3)
Requirement already satisfied: numpy in /home/new/market-prediction/market-env/lib/python3.12/site-packages (from fastparquet) (2.4.0)
Requirement already satisfied: cramjam>=2.3 in /home/new/market-prediction/market-env/lib/python3.12/site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in /home/new/market-prediction/market-env/lib/python3.12/site-packages (from fastparquet) (2026.3.0)
Requirement already satisfied: packaging in /home/new/market-prediction/market-env/lib/python3.12/site-packages (from fastparquet) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/new/market-prediction/market-env/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/new/market-prediction/market-env/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/new/market-prediction/market-env/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2025.3)
Requirement already satisfied: six>=1.5 in /home/new/market-prediction/market-env/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 3.2 MB/s  0:00:15 eta 0:00:010:01:01m
Installing collected packages: pyarrow
Successfully installed pyarrow-24.0.0

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 50)

In [3]:
engine = create_engine(
    "postgresql+psycopg2://market_predict:market_predict@localhost:5432/market_data"
)

In [4]:
spot_query = """
SELECT ts, open, high, low, close, volume
FROM ohlcv
WHERE symbol = 'BTCUSDT'
ORDER BY ts ASC
"""
spot_df_f = pd.read_sql(spot_query, engine)

In [5]:
spot_df_f

,ts,open,high,low,close,volume
0,2017-08-17 00:00:00+00:00,4261.48,4485.39,4200.74,4285.08,795.150377
1,2017-08-18 00:00:00+00:00,4285.08,4371.52,3938.77,4108.37,1199.888264
2,2017-08-19 00:00:00+00:00,4108.37,4184.69,3850.00,4139.98,381.309763
3,2017-08-20 00:00:00+00:00,4120.98,4211.08,4032.62,4086.29,467.083022
4,2017-08-21 00:00:00+00:00,4069.13,4119.62,3911.79,4016.00,691.743060
...,...,...,...,...,...,...
3052,2025-12-25 00:00:00+00:00,87669.44,88592.74,86934.72,87225.27,7096.582350
3053,2025-12-26 00:00:00+00:00,87225.27,89567.75,86655.08,87369.56,18344.615050
3054,2025-12-27 00:00:00+00:00,87369.56,87702.00,87253.05,87483.95,2233.139970
3055,2025-12-28 00:00:00+00:00,87877.00,88088.75,87435.00,87952.71,4446.292850
3056,2025-12-29 00:00:00+00:00,87952.71,90406.08,86806.50,87090.11,13952.010380

In [6]:
CUTOFF = pd.Timestamp("2025-01-29", tz="UTC")

spot_df = spot_df_f[spot_df_f["ts"] <= CUTOFF].copy()
unseen_df = spot_df_f[spot_df_f["ts"] > CUTOFF].copy()

In [7]:
# unseen_df = df[df["ts"] > pd.Timestamp("2025-12-29", tz="UTC")].copy()
unseen_df

,ts,open,high,low,close,volume
2723,2025-01-30 00:00:00+00:00,103733.25,106457.44,103278.54,104722.94,19374.07472
2724,2025-01-31 00:00:00+00:00,104722.94,106012.00,101560.00,102429.56,21983.18193
2725,2025-02-01 00:00:00+00:00,102429.56,102783.71,100279.51,100635.65,12290.95747
2726,2025-02-02 00:00:00+00:00,100635.66,101456.60,96150.00,97700.59,34619.49939
2727,2025-02-03 00:00:00+00:00,97700.59,102500.01,91231.00,101328.52,75164.73850
...,...,...,...,...,...,...
3052,2025-12-25 00:00:00+00:00,87669.44,88592.74,86934.72,87225.27,7096.58235
3053,2025-12-26 00:00:00+00:00,87225.27,89567.75,86655.08,87369.56,18344.61505
3054,2025-12-27 00:00:00+00:00,87369.56,87702.00,87253.05,87483.95,2233.13997
3055,2025-12-28 00:00:00+00:00,87877.00,88088.75,87435.00,87952.71,4446.29285
3056,2025-12-29 00:00:00+00:00,87952.71,90406.08,86806.50,87090.11,13952.01038

In [8]:
spot_df['ts'] = pd.to_datetime(spot_df['ts'], utc=True)
spot_df = spot_df.sort_values('ts').reset_index(drop=True)

assert spot_df['ts'].is_monotonic_increasing
assert spot_df.duplicated(subset=['ts']).sum() == 0

spot_df.head(), spot_df.tail()

(                         ts     open     high      low    close       volume
 0 2017-08-17 00:00:00+00:00  4261.48  4485.39  4200.74  4285.08   795.150377
 1 2017-08-18 00:00:00+00:00  4285.08  4371.52  3938.77  4108.37  1199.888264
 2 2017-08-19 00:00:00+00:00  4108.37  4184.69  3850.00  4139.98   381.309763
 3 2017-08-20 00:00:00+00:00  4120.98  4211.08  4032.62  4086.29   467.083022
 4 2017-08-21 00:00:00+00:00  4069.13  4119.62  3911.79  4016.00   691.743060,
                             ts       open       high        low      close  \
 2718 2025-01-25 00:00:00+00:00  104870.51  105286.52  104106.09  104746.85
 2719 2025-01-26 00:00:00+00:00  104746.86  105500.00  102520.44  102620.00
 2720 2025-01-27 00:00:00+00:00  102620.01  103260.00   97777.77  102082.83
 2721 2025-01-28 00:00:00+00:00  102082.83  103800.00  100272.68  101335.52
 2722 2025-01-29 00:00:00+00:00  101335.52  104782.68  101328.01  103733.24

            volume
 2718   9068.32377
 2719   9812.51238
 2720  50758.13410
 2721  22022.05765
 2722  23155.35802  )

In [9]:
today_utc = pd.Timestamp.utcnow().normalize()
if spot_df['ts'].iloc[-1] >= today_utc:
    spot_df = spot_df.iloc[:-1].reset_index(drop=True)

In [10]:
spot_df['log_return'] = np.log(
    spot_df['close'] / spot_df['close'].shift(1)
)
spot_df = spot_df.dropna(subset=['log_return']).reset_index(drop=True)

In [11]:
train_end = pd.Timestamp("2020-01-01", tz="UTC")
val_end   = pd.Timestamp("2023-01-01", tz="UTC")

def assign_split(ts):
    if ts < train_end:
        return "train"
    elif ts < val_end:
        return "val"
    else:
        return "test"

spot_df["split"] = spot_df["ts"].apply(assign_split)
spot_df["split"].value_counts()

split
val      1096
train     866
test      760
Name: count, dtype: int64

In [12]:
train_returns = spot_df.loc[
    spot_df["split"] == "train", "log_return"
]

q10 = train_returns.quantile(0.10)
q30 = train_returns.quantile(0.30)
q70 = train_returns.quantile(0.70)
q90 = train_returns.quantile(0.90)

q10, q30, q70, q90

(np.float64(-0.04800776698705181),
 np.float64(-0.011619451004109261),
 np.float64(0.014258320311006007),
 np.float64(0.04752814313655959))

In [13]:
def assign_regime(r):
    if r <= q10:
        return 0
    elif r <= q30:
        return 1
    elif r <= q70:
        return 2
    elif r <= q90:
        return 3
    else:
        return 4

spot_df["regime"] = spot_df["log_return"].apply(assign_regime)

spot_df.groupby(["split", "regime"]).size().unstack()

regime   0    1    2    3   4
split
test    23  144  405  156  32
train   87  173  346  173  87
val     81  241  449  242  83

In [14]:
spot_out = spot_df[[
    "ts",
    "open", "high", "low", "close", "volume",
    "log_return",
    "regime",
    "split"
]]

from pathlib import Path

Path("data").mkdir(parents=True, exist_ok=True)

spot_out.to_parquet(
    "data/module1_spot_v0.parquet",
    index=False)

In [15]:
oi_query = """
SELECT ts, symbol, open_interest
FROM open_interest
WHERE symbol = 'BTCUSDT'
ORDER BY ts ASC
"""
oi_df = pd.read_sql(oi_query, engine)

In [16]:
oi_df['ts'] = pd.to_datetime(oi_df['ts'], utc=True)
oi_df = (
    oi_df
    .drop_duplicates(subset=['symbol','ts'], keep='last')
    .sort_values('ts')
    .reset_index(drop=True)
)

In [17]:
calendar = spot_out[['ts']].copy()

oi_aligned = calendar.merge(
    oi_df[['ts','open_interest']],
    on='ts',
    how='left'
)

oi_aligned['oi_change'] = (
    oi_aligned['open_interest'] -
    oi_aligned['open_interest'].shift(1)
)

In [18]:
oi_aligned.to_parquet(
    "data/module1_open_interest_v0.parquet",
    index=False
)

In [19]:
funding_query = """
SELECT ts, symbol, funding_rate
FROM funding_rates
WHERE symbol = 'BTCUSDT'
ORDER BY ts ASC
"""
funding_df = pd.read_sql(funding_query, engine)

In [20]:
funding_df['ts'] = pd.to_datetime(funding_df['ts'], utc=True)

funding_daily = (
    funding_df
    .groupby([
        funding_df['ts'].dt.normalize()
    ])
    .agg({"funding_rate": "mean"})
    .reset_index()
    .rename(columns={"ts": "ts"})
)

funding_aligned = calendar.merge(
    funding_daily,
    on='ts',
    how='left'
)

In [21]:
funding_aligned.to_parquet(
    "data/module1_funding_v0.parquet",
    index=False
)

In [22]:
futures_query = """
SELECT ts, open, high, low, close, volume
FROM futures_ohlcv
WHERE symbol = 'BTCUSDT'
ORDER BY ts ASC
"""
futures_df = pd.read_sql(futures_query, engine)

In [23]:
futures_df['ts'] = pd.to_datetime(futures_df['ts'], utc=True)
futures_df = (
    futures_df
    .drop_duplicates(subset=['ts'], keep='last')
    .sort_values('ts')
    .reset_index(drop=True)
)

futures_df.to_parquet(
    "data/module1_futures_ohlcv_v0.parquet",
    index=False
)

In [24]:
unseen_df.to_parquet("data/unseen_data.parquet",index=False)