In [13]:
import pandas as pd
import numpy as np

# ---- load spot price
price = pd.read_parquet("data/module1_spot_v0.parquet")
price["ts"] = pd.to_datetime(price["ts"], utc=True)
price = price.set_index("ts").sort_index()

# ---- load events
events = pd.read_parquet("data/btc_events.parquet")

# Use THESE for time logic
events["t0_ts"] = pd.to_datetime(events["t0_ts"], utc=True)
events["t1_ts"] = pd.to_datetime(events["t1_ts"], utc=True)


events

,t0,t1,label,ret,sigma,primary_signal,meta_label,uniqueness,sample_weight,primary_pred,...,t1_ts,ts,p0,p1,p2,p3,p4,vol_pred,vol_regime,trend_state
0,21,26,-1,-0.082237,0.051541,1.0,0,0.408333,1.716137,1.0,...,2017-09-13 00:00:00+00:00,2017-09-08,0.368428,0.174742,0.185914,0.178164,0.092752,0.045075,high,up
1,22,26,-1,-0.076619,0.048957,1.0,0,0.290000,1.218807,1.0,...,2017-09-13 00:00:00+00:00,2017-09-09,0.063819,0.106668,0.457580,0.264642,0.107291,0.045075,high,up
2,23,27,-1,-0.258653,0.047303,1.0,0,0.285185,1.198572,1.0,...,2017-09-14 00:00:00+00:00,2017-09-10,0.187509,0.245987,0.230825,0.167934,0.167745,0.045305,high,up
3,24,26,-1,-0.064729,0.045503,1.0,0,0.205556,0.863906,1.0,...,2017-09-13 00:00:00+00:00,2017-09-11,0.211726,0.198270,0.267075,0.236859,0.086070,0.045397,high,up
4,25,26,-1,-0.054039,0.043313,-1.0,1,0.183333,0.770510,1.0,...,2017-09-13 00:00:00+00:00,2017-09-12,0.209975,0.150833,0.432476,0.129632,0.077085,0.045355,high,up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3010,3031,3035,1,0.036802,0.027984,-1.0,0,0.235714,0.990656,1.0,...,2025-12-09 00:00:00+00:00,2025-12-05,0.016994,0.483694,0.437263,0.045924,0.016125,0.026639,low,up
3011,3032,3035,1,0.037846,0.026623,1.0,1,0.233333,0.980649,1.0,...,2025-12-09 00:00:00+00:00,2025-12-06,0.005442,0.442768,0.335275,0.164360,0.052155,0.026541,low,up
3012,3033,3041,-1,-0.044833,0.025750,1.0,0,0.362500,1.523509,1.0,...,2025-12-15 00:00:00+00:00,2025-12-07,0.014930,0.604662,0.327553,0.034013,0.018841,0.025947,low,up
3013,3034,3040,-1,-0.027542,0.024520,1.0,0,0.230000,0.966640,1.0,...,2025-12-14 00:00:00+00:00,2025-12-08,0.008611,0.747666,0.212829,0.021306,0.009588,0.025947,low,up
3014,3035,3038,-1,-0.026352,0.024336,1.0,0,0.205556,0.863906,1.0,...,2025-12-12 00:00:00+00:00,2025-12-09,0.007534,0.400759,0.455795,0.111689,0.024223,0.026582,low,up

In [3]:
def generate_walk_forward_splits(start, end, train_years=3, test_months=6):
    splits = []
    train_delta = pd.DateOffset(years=train_years)
    test_delta = pd.DateOffset(months=test_months)

    train_start = start
    train_end = train_start + train_delta

    while train_end + test_delta <= end:
        test_start = train_end
        test_end = train_end + test_delta

        splits.append((train_start, train_end, test_start, test_end))
        train_end = test_end

    return splits

In [14]:
START = price.index.min()
END   = price.index.max()
print(START,END)
splits = generate_walk_forward_splits(START, END)

ledger = []

for fold_id, (_, _, te_start, te_end) in enumerate(splits):

    test_events = events[
        (events.t0_ts >= te_start) &
        (events.t0_ts <  te_end)
    ]

    for _, ev in test_events.iterrows():

        if ev.meta_label != 1:
            continue

        entry_time = ev.t0_ts + pd.Timedelta(days=1)
        exit_time  = ev.t1_ts

        if entry_time not in price.index or exit_time not in price.index:
            continue

        entry_px = price.loc[entry_time, "open"]
        exit_px  = price.loc[exit_time, "close"]

        ret = ev.primary_pred * (exit_px - entry_px) / entry_px

        ledger.append({
            "event_id": ev.name,
            "fold_id": fold_id,
            "t0_ts": ev.t0_ts,
            "t1_ts": ev.t1_ts,
            "entry_time": entry_time,
            "exit_time": exit_time,
            "direction": ev.primary_pred,
            "ret": ret
        })

2017-08-18 00:00:00+00:00 2025-12-29 00:00:00+00:00

In [15]:
ledger

[{'event_id': 1078,
  'fold_id': 0,
  't0_ts': Timestamp('2020-08-21 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-09-01 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-08-22 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-09-01 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.03388537042449069)},
 {'event_id': 1082,
  'fold_id': 0,
  't0_ts': Timestamp('2020-08-25 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-08-30 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-08-26 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-08-30 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.0346991894628402)},
 {'event_id': 1087,
  'fold_id': 0,
  't0_ts': Timestamp('2020-08-30 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-09-02 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-08-31 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-09-02 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(-0.027548912704708342)},
 {'event_id': 1089,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-01 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-09-02 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-02 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-09-02 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(-0.044743444246210864)},
 {'event_id': 1090,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-02 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-09-03 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-03 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-09-03 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(-0.10955662446634955)},
 {'event_id': 1103,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-15 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-16 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(-0.034121664535665924)},
 {'event_id': 1104,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-16 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-17 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(-0.04900397206137304)},
 {'event_id': 1105,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-17 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-18 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(-0.047786106032906825)},
 {'event_id': 1106,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-18 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-19 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(-0.047211297492088494)},
 {'event_id': 1107,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-19 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-20 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(-0.059871992953475624)},
 {'event_id': 1108,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-20 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(-0.046066584373294577)},
 {'event_id': 1109,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-21 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-09-24 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-22 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-09-24 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.030631972829603327)},
 {'event_id': 1111,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-23 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-09-24 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-24 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-09-24 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.04831928260228528)},
 {'event_id': 1112,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-24 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-09 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-25 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-09 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.029275366908431417)},
 {'event_id': 1113,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-25 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-09 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-26 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-09 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.03406799375290666)},
 {'event_id': 1114,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-26 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-09 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-27 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-09 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.030017924070171315)},
 {'event_id': 1115,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-27 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-09 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-28 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-09 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.025651877715963712)},
 {'event_id': 1116,
  'fold_id': 0,
  't0_ts': Timestamp('2020-09-28 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-09 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-09-29 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-09 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.03314569502370477)},
 {'event_id': 1119,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-01 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-08 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-02 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-08 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.02885735460437913)},
 {'event_id': 1120,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-02 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-05 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-03 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-05 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.020984068720199756)},
 {'event_id': 1127,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-09 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-10 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-10 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-10 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.02195166976754287)},
 {'event_id': 1128,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-10 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-12 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-11 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-12 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.020811602005451117)},
 {'event_id': 1129,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-11 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-19 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-12 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-19 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.03363966287331704)},
 {'event_id': 1131,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-13 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-19 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-14 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-19 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.028974035446566997)},
 {'event_id': 1132,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-14 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-19 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-15 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-19 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.029215555588642028)},
 {'event_id': 1134,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-16 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-18 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-17 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-18 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.01624667380495507)},
 {'event_id': 1135,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-17 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-19 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-18 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-19 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.034432158981577074)},
 {'event_id': 1136,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-18 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-19 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-19 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-19 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.02158801857579756)},
 {'event_id': 1137,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-19 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-21 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-20 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-21 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.08760613574823894)},
 {'event_id': 1138,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-20 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-21 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-21 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-21 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.07312846347607045)},
 {'event_id': 1139,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-21 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-24 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-22 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-24 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.025896758797410133)},
 {'event_id': 1140,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-22 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-27 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-23 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-27 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.0514564139892234)},
 {'event_id': 1141,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-23 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-27 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-24 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-27 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.05518120321348045)},
 {'event_id': 1142,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-24 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-27 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-25 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-27 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.03999777298647856)},
 {'event_id': 1143,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-25 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-27 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-26 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-27 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.0465500198010076)},
 {'event_id': 1144,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-26 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-27 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-27 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-27 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.04474511862030397)},
 {'event_id': 1146,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-28 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-31 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-29 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-31 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.03954350841222942)},
 {'event_id': 1147,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-29 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-10-31 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-30 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-10-31 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.02491956934204039)},
 {'event_id': 1148,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-30 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-03 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-10-31 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-03 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.03417600165190524)},
 {'event_id': 1149,
  'fold_id': 0,
  't0_ts': Timestamp('2020-10-31 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-04 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-01 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-04 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.025597128562105737)},
 {'event_id': 1150,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-01 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-04 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-02 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-04 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.027796408673770097)},
 {'event_id': 1151,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-02 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-03 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-03 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-03 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.03497512478200523)},
 {'event_id': 1152,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-03 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-05 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-04 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-05 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.11170439967682885)},
 {'event_id': 1153,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-04 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-05 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-05 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-05 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.10223479762811255)},
 {'event_id': 1156,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-07 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-08 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-08 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-08 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.044323572879480175)},
 {'event_id': 1157,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-08 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-12 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-09 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-12 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.05277898042662084)},
 {'event_id': 1158,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-09 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-12 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-10 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-12 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.06285387721231366)},
 {'event_id': 1159,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-10 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-12 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-11 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-12 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.06502166081265809)},
 {'event_id': 1160,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-11 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-12 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-12 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-12 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.03874013739898309)},
 {'event_id': 1161,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-12 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-17 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-13 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-17 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.08393951577015506)},
 {'event_id': 1162,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-13 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-17 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-14 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-17 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.08206720081568428)},
 {'event_id': 1163,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-14 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-16 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-15 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-16 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.040076392881945755)},
 {'event_id': 1164,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-15 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-16 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-16 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-16 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.04741304756533181)},
 {'event_id': 1165,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-16 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-17 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-17 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-17 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.05662032372249754)},
 {'event_id': 1166,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-17 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-20 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-18 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-20 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.05641704295394273)},
 {'event_id': 1167,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-18 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-20 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-19 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-20 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.04938307716105796)},
 {'event_id': 1168,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-19 00:00:00+0000', tz='UTC'),
  't1_ts': Timestamp('2020-11-20 00:00:00+0000', tz='UTC'),
  'entry_time': Timestamp('2020-11-20 00:00:00+0000', tz='UTC'),
  'exit_time': Timestamp('2020-11-20 00:00:00+0000', tz='UTC'),
  'direction': 1.0,
  'ret': np.float64(0.04790592046985823)},
 {'event_id': 1171,
  'fold_id': 0,
  't0_ts': Timestamp('2020-11-22 00:00:00+0000', tz='UTC'),

In [16]:
ledger = pd.DataFrame(ledger).sort_values("exit_time").reset_index(drop=True)

ledger["cum_pnl"] = ledger["ret"].cumsum()
ledger["peak"] = ledger["cum_pnl"].cummax()
ledger["drawdown"] = ledger["cum_pnl"] - ledger["peak"]

mean_ret = ledger.ret.mean()
hit_rate = (ledger.ret > 0).mean()
max_dd = ledger.drawdown.min()

sharpe = (
    mean_ret / ledger.ret.std() * np.sqrt(252)
    if ledger.ret.std() > 0 else np.nan
)

print("Trades:", len(ledger))
print("Mean return:", mean_ret)
print("Hit rate:", hit_rate)
print("Sharpe:", sharpe)
print("Max drawdown:", max_dd)

Trades: 911
Mean return: 0.010236202065906874
Hit rate: 0.6114160263446762
Sharpe: 3.0040709015201505
Max drawdown: -5.5538377029167725

In [17]:
ledger.groupby("fold_id")["ret"].agg(["count", "mean", "sum"])

         count      mean       sum
fold_id
0          113  0.051766  5.849606
1           86 -0.013888 -1.194371
2           91 -0.010211 -0.929192
3           80 -0.015720 -1.257611
4           84  0.003869  0.324963
5           84  0.005676  0.476791
6          105  0.029421  3.089177
7           93  0.004224  0.392796
8           90  0.021346  1.921119
9           85  0.007669  0.651903

In [18]:
ledger.groupby("exit_time").size().describe()

count    394.000000
mean       2.312183
std        1.937051
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max       16.000000
dtype: float64

In [19]:
cost = 0.002  # 20 bps
ledger["ret_net"] = ledger["ret"] - cost

ledger["ret_net"].mean()
ledger["ret_net"].cumsum().iloc[-1]
ledger["ret_net"].min()

np.float64(-0.15928620640075045)

In [20]:
# ----------------------------------
# Save baseline ledger
# ----------------------------------
ledger = ledger.copy()

# Enforce types (important)
ledger["fold_id"] = ledger["fold_id"].astype(int)
ledger["exit_time"] = pd.to_datetime(ledger["exit_time"], utc=True)
ledger["entry_time"] = pd.to_datetime(ledger["entry_time"], utc=True)

ledger.to_parquet(
    "data/ledger_baseline.parquet",
    engine="pyarrow",
    index=False
)

print("Saved:", ledger.shape)

Saved: (911, 12)

In [21]:
# Required columns check
required_cols = {
    "t0_ts", "t1_ts",
    "primary_pred", "primary_prob",
    "meta_label", "sigma",
    "vol_regime", "trend_state",
    "fold_id"
}

missing = required_cols - set(ledger.columns)
assert not missing, f"Missing columns: {missing}"

KeyboardInterrupt